### ISSUE TITLE
General help

### ISSUE THREAD

**Issue by mrityuShell** [m4ll0k/Bug-Bounty-Toolz#12]
Hello team , 
I just wanna ask , how can we parse a list of js file urls in jsalert.py ?

**Comment by m4ll0k** [comment]
`$ cat myjs.txt | xargs -I @ bash -c "python3 jsalert.py @"  `

**Comment by m4ll0k** [comment]
or `$ cat myjs.txt | xargs -I @ bash -c 'echo -e "\n[URL] @\n";python3 jsalert.py @'`
