### ISSUE TITLE
Getjsword.py 

### ISSUE THREAD

**Issue by xhatanubiss** [m4ll0k/Bug-Bounty-Toolz#4]
Hello, i wanted to use the tool but facing a problem.

When i use "cat filename.txt | python3 getjsword.py" it always shows the usage message.

But when i use python3 getjsword.py https://domain.com it works but not working for the above.

Any help?

**Comment by m4ll0k** [comment]
show me the content in `filename.txt`

**Comment by m4ll0k** [comment]
resolved!!
